### ISSUE TITLE
Error: the procedure entry point __kmpc_disaptch_deinit could not be located in the dynamic link library ggml-base.dll

### ISSUE THREAD

**Issue by flylifeny** [Tavris1/ComfyUI-Easy-Install#248]
Fresh install. Receive the error below 3x during startup, which also stalls startup until confirmation is clicked. It seems to be caused by custom node: ComfyUI-QwenVL, which is not updated with the new LlamaCPP GGLM backend. The node seems to still work from a quick test I did. Is there a reason why this custom node is still included with the default install package? The node hasn't been updated in a few months.

### **Console Output:**
Windows fatal exception: code 0xc0000139

Error loading module AILab_QwenVL_GGUF_PromptEnhancer: Failed to load 'ggml' from [WindowsPath('C:/ComfyUI2026July/ComfyUI-Easy-Install/python_embeded/Lib/site-packages/llama_cpp/lib'), WindowsPath('C:/ComfyUI2026July/ComfyUI-Easy-Install/python_embeded/Lib/site-packages/llama_cpp/bin')]
C:\ComfyUI2026July\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\llama_cpp\bin\ggml.dll: [WinError 127] The specified procedure could not be found
C:\ComfyUI2026July\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\llama_cpp\lib\ggml.dll: [WinError 127] The specified procedure could not be found
C:\ComfyUI2026July\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\llama_cpp\bin\ggml.dll: [WinError 127] The specified procedure could not be found
Library search path contents:
C:\ComfyUI2026July\ComfyUI-Easy-Install\python_embeded\Lib\site-packages\llama_cpp\lib:
  - ggml-base.dll
  - ggml-cpu-alderlake.dll
  - ggml-cpu-cannonlake.dll
  - ggml-cpu-cascadelake.dll
  - ggml-cpu-cooperlake.dll
  - ggml-cpu-haswell.dll
  - ggml-cpu-icelake.dll
  - ggml-cpu-ivybridge.dll
  - ggml-cpu-piledriver.dll
  - ggml-cpu-sandybridge.dll
  - ggml-cpu-sapphirerapids.dll
  - ggml-cpu-skylakex.dll
  - ggml-cpu-sse42.dll
  - ggml-cpu-x64.dll
  - ggml-cpu-zen4.dll
  - ggml-cuda.dll
  - ggml.dll
  - libomp140.x86_64.dll
  - llama-common.dll
  - llama.dll
  - mtmd.dll

**Comment by Tavris1** [comment]
I can't reproduce this issue.
It looks like the latest llama-cpp-python wheel isn't compatible with your system.

Please try installing the previous wheel and let me know if that resolves the problem.
From the `python_embeded` folder run these commands:
```console
.\python.exe -m pip uninstall llama-cpp-python -y
```
```console
.\python.exe -m pip install https://github.com/JamePeng/llama-cpp-python/releases/download/v0.3.33-cu130-Basic-win-20260315/llama_cpp_python-0.3.33+cu130.basic-cp312-cp312-win_amd64.whl
```

**Comment by flylifeny** [comment]
That seems to have solved it. Before this recent install, I was running an early May 2026 ez-install build and it was working fine.

To resolve this issue going forward with future installs, is it possible I need to update VC++ runtime libraries as referenced below? It seems others had the same error. https://github.com/JamePeng/llama-cpp-python/issues/138#issuecomment-4756327859

**Comment by 4rc4nux** [comment]
Have the same issue.

Just Updated Torch pack to 2.10.0+cu130 and that error started to appear. Comfy still launches after ignoring the 7+ warning popup windows.
Reverted back to 2.9.1+cu130 but the errors still pop up.

Edit: Uninstalling and Reinstalling llama-cpp-python fixed the issue. Nunchacku fails to load though....
Edit2: Tried 2.10.0 again. Reinstalled llama-cpp-python again to fix the errors. Nunchaku loads fine now.

**Comment by Tavris1** [comment]
Guys, try the steps from lylifeny's comment: https://github.com/Tavris1/ComfyUI-Easy-Install/issues/248#issuecomment-4859758164

**Comment by flylifeny** [comment]
Another few attempts on fresh install:
Uninstalled all C++ runtime libraries. Reinstall only 2015-2022 C++ library.  (from JamePeng's comment)
Still have the same error.

Uninstall llama cpp python + Reinstall v0.3.40-cu130-win-20260608/llama_cpp_python-0.3.40+cu130-cp312-cp312-win_amd64.whl
Error remains.

Uninstall llama cpp python + Install v0.3.33-cu130-Basic-win-20260315/llama_cpp_python-0.3.33+cu130.basic-cp312-cp312-win_amd64.whl
No error.

Uninstall llama cpp python + Install v0.3.38-cu130-Basic-win-20260504/llama_cpp_python-0.3.38+cu130.basic-cp312-cp312-win_amd64.whl
No error

   Python    : 3.12
   PyTorch   : 2.9
   CUDA Core : 13.0
   NVIDIA-drv: 610.62 -- 5090

**Comment by Tavris1** [comment]
Thanks for the test.
I'll downgrade the llama-cpp version in the next CEI release.

**Comment by JamePeng** [comment]
This issue primarily stemmed from an inconsistency in early version 0.3.40, where the VC143 build conflicted with the copied VC142 `libomp140.x86_64.dll`, preventing ggml from correctly loading the dynamic library. Version 0.3.41-preview has resolved this and optimized the library loading priority, while versions 0.3.42–0.3.43 include optimizations for the generic `GenericMTMDChatHandler`. We welcome your testing and feedback.😉

**Comment by Tavris1** [comment]
@JamePeng Thank you for the detailed explanation and for fixing this issue in the newer llama-cpp-python builds!
I really appreciate the work you are putting into maintaining and improving the wheels.

@flylifeny @4rc4nux, could you please try the latest llama-cpp-python version and let us know if this resolves the issue for you?

I have not been able to reproduce this problem on my setup.
It would be great to confirm that the latest version fixes the issue for affected users.

**Comment by 4rc4nux** [comment]
@Tavris1 
> [@flylifeny](https://github.com/flylifeny) [@4rc4nux](https://github.com/4rc4nux), could you please try the latest llama-cpp-python version and let us know if this resolves the issue for you?
> 
> I have not been able to reproduce this problem on my setup. It would be great to confirm that the latest version fixes the issue for affected users.

No problem but, not sure how to do it properly.

Have to install one of this wheels? https://github.com/JamePeng/llama-cpp-python/releases/#release-v0.3.43-cu130-win-20260717

If so, not sure which one... Probably this one, right? llama_cpp_python-0.3.43+cu130-cp312-cp312-win_amd64.whl

BTW, EZi has been working great with the downgraded version you provided previously.

**Comment by Tavris1** [comment]
@4rc4nux 
From the `python_embeded` folder run this command:
```console
.\python.exe -m pip install -U https://github.com/JamePeng/llama-cpp-python/releases/download/v0.3.43-cu130-win-20260717/llama_cpp_python-0.3.43+cu130-cp312-cp312-win_amd64.whl
```

**Comment by 4rc4nux** [comment]
@Tavris1 

No luck with 0.3.43. Same error

Reverting to 0.3.33 works fine.

Additional errors on the Console:

Error loading module AILab_QwenVL_GGUF: Failed to load 'ggml-base' from [WindowsPath('I:/ComfyUI-EZi/python_embeded/Lib/site-packages/llama_cpp/lib'), WindowsPath('I:/ComfyUI-EZi/python_embeded/Lib/site-packages/llama_cpp/bin')]
I:\ComfyUI-EZi\python_embeded\Lib\site-packages\llama_cpp\lib\ggml-base.dll: [WinError 127] Impossível localizar o procedimento especificado
I:\ComfyUI-EZi\python_embeded\Lib\site-packages\llama_cpp\lib\ggml-base.dll: [WinError 127] Impossível localizar o procedimento especificado
I:\ComfyUI-EZi\python_embeded\Lib\site-packages\llama_cpp\bin\ggml-base.dll: [WinError 127] Impossível localizar o procedimento especificado
Library search path contents:
I:\ComfyUI-EZi\python_embeded\Lib\site-packages\llama_cpp\lib:
  - ggml-base.dll
  - ggml-cpu-alderlake.dll
  - ggml-cpu-cannonlake.dll
  - ggml-cpu-cascadelake.dll
  - ggml-cpu-cooperlake.dll
  - ggml-cpu-haswell.dll
  - ggml-cpu-icelake.dll
  - ggml-cpu-ivybridge.dll
  - ggml-cpu-piledriver.dll
  - ggml-cpu-sandybridge.dll
  - ggml-cpu-sapphirerapids.dll
  - ggml-cpu-skylakex.dll
  - ggml-cpu-sse42.dll
  - ggml-cpu-x64.dll
  - ggml-cpu-zen4.dll
  - ggml-cuda.dll
  - ggml.dll
  - libomp140.x86_64.dll
  - llama-common.dll
  - llama.dll
  - mtmd.dll
I:\ComfyUI-EZi\python_embeded\Lib\site-packages\llama_cpp\bin:
  - ggml-base.dll
  - ggml-cpu-alderlake.dll
  - ggml-cpu-cannonlake.dll
  - ggml-cpu-cascadelake.dll
  - ggml-cpu-cooperlake.dll
  - ggml-cpu-haswell.dll
  - ggml-cpu-icelake.dll
  - ggml-cpu-ivybridge.dll
  - ggml-cpu-piledriver.dll
  - ggml-cpu-sandybridge.dll
  - ggml-cpu-sapphirerapids.dll
  - ggml-cpu-skylakex.dll
  - ggml-cpu-sse42.dll
  - ggml-cpu-x64.dll
  - ggml-cpu-zen4.dll
  - ggml-cuda.dll
  - ggml.dll
  - llama-common.dll
  - llama.dll
  - mtmd.dll

**Comment by JamePeng** [comment]
Currently, the path priority logic in the `llama-cpp-python` library prioritizes the `lib` file located in the installation directory; however, the path can evidently be altered again when third-party plugins utilize the library—a known weakness of the `find_library` function. I also suspect that the issue might stem from the presence of a different version of `libomp140.x86_64.dll` (i.e., one other than the VC143 version) somewhere else on the system，like C:\WINDOWS\SYSTEM32\libomp140.x86_64.dll

**Comment by 4rc4nux** [comment]
@JamePeng 

Just checked for libomp140.x86_64.dll in System32 and yes, it's there. libomp140d.x86_64.dll too if that's relevant.
Both have a modified date of 20/10/2024. Again, if that's relevant info ;)

Reverting back to 0.3.33 and the errors go away...

**Comment by JamePeng** [comment]
@4rc4nux I've submitted a fix; could you replace those two files and test it out?

**Comment by 4rc4nux** [comment]
@JamePeng 
> [@4rc4nux](https://github.com/4rc4nux) I've submitted a fix; could you replace those two files and test it out?

Not sure what to replace though...

Replace libomp140.x86_64.dll and libomp140d.x86_64.dll on System 32 with the ones in site-packages\llama_cpp\lib\ or vice-versa? Or something else i'm not understanding?

**Comment by JamePeng** [comment]
@4rc4nux https://github.com/JamePeng/llama-cpp-python/commit/0eb26153ff757498c22c4574c3edabe7e19b2ad5

**Comment by 4rc4nux** [comment]
@JamePeng 

Working fine with 0.3.43 and those 2 files replaced.

Console log:

[llama-cpp-python] loaded bundled OpenMP runtime: I:\ComfyUI-EZi\python_embeded\Lib\site-packages\llama_cpp\lib\libomp140.x86_64.dll
[llama-cpp-python].find_library: loaded library from I:\ComfyUI-EZi\python_embeded\Lib\site-packages\llama_cpp\lib\ggml-base.dll
[llama-cpp-python].find_library: loaded library from I:\ComfyUI-EZi\python_embeded\Lib\site-packages\llama_cpp\lib\ggml.dll
[llama-cpp-python].find_library: loaded library from I:\ComfyUI-EZi\python_embeded\Lib\site-packages\llama_cpp\lib\llama.dll
Error loading module AILab_QwenVL_GGUF: Path.rglob() got an unexpected keyword argument 'recurse_symlinks'
[QwenVL] Loaded 13 cached prompts
[QwenVL Debug] SAGE_ATTENTION_AVAILABLE: True
[QwenVL Debug] CUDA capability: 8.9
[QwenVL Debug] Final ATTENTION_MODES: ['auto', 'sage', 'flash_attention_2', 'sdpa']
[QwenVL] NOTE: SageAttention option shown for testing. Install with: pip install sageattention

Thanks for looking into it! Much appreciated!

**Comment by JamePeng** [comment]
Okay, I'm going to release a minor update, version 0.3.44.
