### ISSUE TITLE
TeaCache node and latest ComfyUI, unable to import. Fails to load at startup.

### ISSUE THREAD

**Issue by essence25** [Tavris1/ComfyUI-Easy-Install#95]
Based on my research it appears that TeaCache node is  broken due to updated ComfyUI:

ComfyUI v0.8.0 (Jan 7 2026) refactored the Lightricks internals
precompute_freqs_cis no longer exists or moved
teacache is coded against an older ComfyUI API and this breaks it.

Are you able to import TeaCache successfully on your end with ComfyUI v0.80 (2.9.1+cu130) ?
I tried both ComfyUI-Teacache and teacache installs via git clone and from within the manager same result.

Te exact error message:

Traceback (most recent call last):
  File "J:\_EZi\CFi-EZi\ComfyUI\nodes.py", line 2155, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "J:\_EZi\CFi-EZi\ComfyUI\custom_nodes\teacache\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS as NODES_CLASS, NODE_DISPLAY_NAME_MAPPINGS as NODES_DISPLAY
  File "J:\_EZi\CFi-EZi\ComfyUI\custom_nodes\teacache\nodes.py", line 12, in <module>
    from comfy.ldm.lightricks.model import precompute_freqs_cis
ImportError: cannot import name 'precompute_freqs_cis' from 'comfy.ldm.lightricks.model' (J:\_EZi\CFi-EZi\ComfyUI\comfy\ldm\lightricks\model.py)

Cannot import J:\_EZi\CFi-EZi\ComfyUI\custom_nodes\teacache module for custom nodes: cannot import name 'precompute_freqs_cis' from 'comfy.ldm.lightricks.model' (J:\_EZi\CFi-EZi\ComfyUI\comfy\ldm\lightricks\model.py)

**Comment by Tavris1** [comment]
Unfortunately, TeaCache works with ComfyUI version up to 0.6.0

I will disable it next week if things don't improve, because Ioan/Pixaroma is currently preparing a video showing how to proceed with such issues.

Of course, the ComfyUI version can easily be changed from the **ComfyUI folder** with these commands:
```console
git.exe checkout v0.6.0
```
Revert back to the latest version:
```console
git.exe checkout master
```

**Comment by essence25** [comment]
Here is the fix for TeaCache:


    Open the file nodes.py inside the TeaCache folder in Comfy's custom_nodes folder (custom_nodes/teacache)
    Find line 12 that has this import: "from comfy.ldm.lightricks.model import precompute_freqs_cis"
    Replace it with: "from comfy.ldm.lightricks.model import LTXBaseModel"
    Find line 631:  "pe = precompute_freqs_cis(fractional_coords, dim=self.inner_dim, out_dtype=x.dtype)"
    Replace it with: "pe = LTXBaseModel.precompute_freqs_cis(fractional_coords, dim=self.inner_dim, out_dtype=x.dtype)"
    Restart Comfy.

No more error and TeaCache loads in ComfyUI v0.82

Credit to @Walkdao

**Comment by VenimK** [comment]
`#!/bin/bash

# Title: TeaCache Fix for 'ComfyUI Easy Install' by ivo
# Pixaroma Community Edition
# Fixes the precompute_freqs_cis import issue in TeaCache nodes.py

cd "$(dirname "$0")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RESET='\033[0m'

echo -e "${GREEN}::::::::::::::: TeaCache Fix :::::::::::::::${RESET}"
echo ""

# Find TeaCache nodes.py
TEACACHE_DIR="../ComfyUI/custom_nodes/teacache"
NODES_FILE="$TEACACHE_DIR/nodes.py"

if [ ! -f "$NODES_FILE" ]; then
    echo -e "${RED}✗ TeaCache nodes.py not found at: $NODES_FILE${RESET}"
    echo -e "${YELLOW}Make sure TeaCache is installed in custom_nodes/teacache${RESET}"
    exit 1
fi

echo -e "${GREEN}✓${RESET} Found TeaCache nodes.py"

# Create backup
BACKUP_FILE="$NODES_FILE.backup"
if [ ! -f "$BACKUP_FILE" ]; then
    cp "$NODES_FILE" "$BACKUP_FILE"
    echo -e "${GREEN}✓${RESET} Created backup: nodes.py.backup"
else
    echo -e "${YELLOW}✓${RESET} Backup already exists"
fi

# Check if fix is already applied
if grep -q "from comfy.ldm.lightricks.model import LTXBaseModel" "$NODES_FILE"; then
    echo -e "${YELLOW}✓${RESET} Fix already applied - nodes.py is up to date"
    echo ""
    echo -e "${GREEN}::::::::::::::: No changes needed :::::::::::::::${RESET}"
    exit 0
fi

# Apply fix 1: Replace import statement
echo -e "${CYAN}Applying fix 1: Updating import statement...${RESET}"
if grep -q "from comfy.ldm.lightricks.model import precompute_freqs_cis" "$NODES_FILE"; then
    sed -i.tmp 's/from comfy\.ldm\.lightricks\.model import precompute_freqs_cis/from comfy.ldm.lightricks.model import LTXBaseModel/' "$NODES_FILE"
    rm -f "$NODES_FILE.tmp"
    echo -e "${GREEN}✓${RESET} Import statement updated"
else
    echo -e "${YELLOW}!${RESET} Import statement not found (may already be fixed or different version)"
fi

# Apply fix 2: Replace function call
echo -e "${CYAN}Applying fix 2: Updating function call...${RESET}"
if grep -q "pe = precompute_freqs_cis(" "$NODES_FILE"; then
    sed -i.tmp 's/pe = precompute_freqs_cis(/pe = LTXBaseModel.precompute_freqs_cis(/' "$NODES_FILE"
    rm -f "$NODES_FILE.tmp"
    echo -e "${GREEN}✓${RESET} Function call updated"
else
    echo -e "${YELLOW}!${RESET} Function call not found (may already be fixed or different version)"
fi

# Verify fix
echo ""
echo -e "${CYAN}Verifying fix...${RESET}"
if grep -q "from comfy.ldm.lightricks.model import LTXBaseModel" "$NODES_FILE" && \
   grep -q "pe = LTXBaseModel.precompute_freqs_cis(" "$NODES_FILE"; then
    echo -e "${GREEN}✓${RESET} Fix verified successfully!"
    echo ""
    echo -e "${GREEN}::::::::::::::: TeaCache Fix Complete :::::::::::::::${RESET}"
    echo -e "${YELLOW}Please restart ComfyUI for changes to take effect.${RESET}"
else
    echo -e "${RED}✗${RESET} Fix verification failed"
    echo -e "${YELLOW}You may need to manually edit nodes.py${RESET}"
    echo ""
    echo -e "Required changes:"
    echo -e "  Line 12: from comfy.ldm.lightricks.model import LTXBaseModel"
    echo -e "  Line 631: pe = LTXBaseModel.precompute_freqs_cis(...)"
fi
`

Run from Add-Ons map

**Comment by Tavris1** [comment]
To close the topic, I will say, this problem has a simpler solution, but it should be done by the guys behind TeaCache and not ComfyUI-Easy-Install.

If this is not done after the new Pixaroma video is released, I will probably disable or remove the node until the problem is fixed.
