### ISSUE TITLE
Update scripts force-downgrade NumPy to 1.26.4, breaking NumPy-2 packages on any install

### ISSUE THREAD

**Issue by nevilex** [Tavris1/ComfyUI-Easy-Install#261]
## Summary

`Update ComfyUI.bat` and `Update ComfyUI and Nodes.bat` unconditionally force-reinstall `numpy==1.26.4`. A fresh install lands on **NumPy 2.x** (the installer no longer pins NumPy, and ComfyUI's `requirements.txt` specifies `numpy>=1.25.0`), so the **first run of either update script downgrades NumPy by a major version**. Packages built against the NumPy 2.x C ABI then fail to import.

## The offending block

Identical in both scripts:

```bat
:: Restoring Numpy 1.26.4 ::
%PYTHON_EXE% -c "import numpy, sys; sys.exit(0 if numpy.__version__ == '1.26.4' else 1)" 2>nul || %PYTHON_EXE% -I -m pip install --force-reinstall numpy==1.26.4 --no-deps --no-warn-script-location
```

- `Update ComfyUI.bat` — lines 19–20
- `Update ComfyUI and Nodes.bat` — lines 27–28

Because of `--no-deps`, pip raises no conflict at install time; the breakage only shows up later at import.

## Why it breaks a stock install

These packages aren't ComfyUI-core or Easy-Install direct dependencies — but they're declared by the **default bundled custom nodes**, so a stock install is affected with no third-party nodes added:

| Package | Requires | Declared by (all bundled) |
| --- | --- | --- |
| `opencv-python` | `numpy>=2` (Python ≥ 3.9) | ControlNet-Aux, RMBG, KJNodes, SeedVR2, LayerStyle, WanVideoWrapper, WanAnimatePreprocess, Easy-Use |
| `colour-science` | `numpy<3,>=2.0.0` | LayerStyle |
| `tifffile` (via scikit-image) | `numpy>=2.1` | ControlNet-Aux |

After the forced downgrade to 1.26.4 these constraints are all violated, and packages with C extensions built against the NumPy 2 ABI (opencv in particular) fail to import with the usual `numpy.dtype size changed` / `module compiled against API version` error.

## Reproduce

1. Fresh install (lands on NumPy 2.x).
2. Run `Update ComfyUI.bat` (or `Update ComfyUI and Nodes.bat`) once.
3. `python_embeded\python.exe -m pip check` now reports the NumPy constraint violations; `python_embeded\python.exe -c "import cv2"` fails; `numpy.__version__` is `1.26.4`.

## Expected vs actual

- **Expected:** the update leaves NumPy at the 2.x version the installer targets.
- **Actual:** NumPy is downgraded to 1.26.4 and the NumPy-2 stack breaks.

## Notes

- The block is **self-restoring**: editing it out of the root `.bat` doesn't hold, because `Update Easy-Install.bat` → `AutoRun.bat` copies fresh update scripts (still containing the line) from `Helper-CEI.zip` back to the install root.
- The stock ComfyUI updaters under `update\` (`update_comfyui_stable.bat`, `update_comfyui.bat`) do **not** contain this line — it's added only by these wrapper scripts.

## Suggested fix

Remove the `Restoring Numpy 1.26.4` block. It's inconsistent with the installer, which already dropped its NumPy pin and builds on NumPy 2.x. If a specific dependency still needs NumPy < 2, pin that package rather than globally force-downgrading NumPy with `--no-deps`.

## Environment

- ComfyUI-Easy-Install v3.11.1 (update scripts observed on a v3.10.0 install; v3.11.1's copies in `Helper-CEI.zip` are byte-identical)
- Python 3.12.10 (embedded), Windows 11
- torch 2.10.0+cu130

**Comment by nevilex** [comment]
Not sure if this is intentional since a fresh install already has Numpy 2.x.

**Comment by Tavris1** [comment]
Thanks for the detailed report.

The `numpy==1.26.4` pin is intentional.
It was added because several components (for example, Nunchaku) do not work with NumPy 2.x
The goal was to provide a configuration that works for the largest number of users out of the box.

If you prefer a different NumPy version, there is a way to override it:
**Menu > Advanced > PINNED PACKAGES MANAGER**.

You can add your own package pin there, for example:

```console
numpy>=2.1
```

However, switching to NumPy 2.x is not guaranteed to be compatible with every node.

One question, though - although many packages declare `numpy>=2`, what is actually failing in your installation?
Aside from `pip check` reporting version constraint mismatches, which nodes or workflows are not working?
Are you seeing actual runtime errors, or only dependency warnings?

**Comment by nevilex** [comment]
Thanks! Ok that makes sense. I stopped using Nunchaku since it seems stale with no new models for it but it would be good for people who still use it. After the whole kornia saga with LTX 2.3 a couple of weeks ago, I've been very cautious with updates.

So I ran some more thorough tests and it looks like I overstated the breakage.

First test, in an isolated venv with the exact versions from my install, opencv-python (5.0.0.93) and colour-science (0.4.7) both import and run fine under NumPy 1.26.4 the numpy>=2 declarations are metadata, not a runtime barrier there. The only genuine runtime failure I found was tifffile (2026.6.1): imread() calls reshape(shape, copy=False), and copy= on reshape is NumPy 2.1+ only, so it throws TypeError under 1.26.4 but only for workflows that actually read TIFFs. It's a dependency for ComfyStereo through scikit-image but it looks like for my workflows, I don't need it anyway since I don't use TIFFs.

Second test, I ran the real update on a throwaway copy of my install. The downgrade happened as expected (2.4.6 -> 1.26.4) — but on the next ComfyUI startup, ComfyUI-Manager's dependency reinstall pulled NumPy right back to 2.4.6 (frame-interpolation -> opencv-contrib-python numpy>=2, then rmbg -> transparent-background). So on a Manager-managed install whose nodes need NumPy≥2, the 1.26.4 pin doesn't even persist a single launch and everything loaded clean throughout. It's probably why I couldn't use Nunchaku a couple of months ago.

On the Pinned Packages Manager: in the launcher version I have it might only apply to entries containing == (it skips others), so numpy>=2.1 could be silently ignored.  if not _entry or '==' not in _entry: continue on ComfyUI-EZi.py.

I used numpy==2.4.6. And it's applied by the desktop launcher, so it doesn't take effect for users who start via Start ComfyUI.bat directly. Neither is urgent. I still like running it on a separate console window on another screen next to task manager showing GPU Utilization. I was using the standalone desktop app before but I kept opening the console window at the bottom.

I'm just testing a few of my main workflows now to see if anything is affected. LTX 2.3 and FlashVSR are ok so far.

**Comment by Tavris1** [comment]
The question above was rhetorical. 🙂
Almost everything will work with Numpy 1.26.4, but everyone can decide what works best for their own setup.

Regarding the separate console window, you can already do that in the Desktop version:
**Menu > Appearance > Detach console to standalone cmd window**

**Comment by nevilex** [comment]
Ah sweet! I'll try that on my next run. Thanks for all the hard work you guys put in btw. The amount of hours you save thousands of people setting up ComfyUI's a huge help. ^_^

**Comment by Tavris1** [comment]
You're welcome! 🙂
And thanks for taking the time to test everything so thoroughly and report back with actual results.
That's just as valuable as reporting bugs.
I hope the detached console makes your workflow a bit nicer. 🙂

**Comment by lolxdmainkaisemaanlu** [comment]
I’m seeing a genuine ComfyUI startup failure caused by the NumPy 1.26.4 pin, not only `pip check` warnings.

My installed versions are:

```text
NumPy: 1.26.4
SciPy: 1.18.0
```

SciPy 1.18.0 explicitly requires:

```text
numpy>=2.0.0,<2.8
```

When starting ComfyUI, SciPy first reports:

```text
UserWarning: A NumPy version >=2.0.0 and <2.8.0 is required for this version of SciPy
(detected version 1.26.4)
```

ComfyUI then crashes during its normal sampler imports:

```text
ComfyUI main.py
→ comfy.samplers
→ comfy.k_diffusion.sampling
→ scipy.integrate
→ scipy.sparse
```

The final exception is:

```text
AttributeError: module 'numpy' has no attribute 'long'. Did you mean: 'log'?
```

So ComfyUI itself cannot launch with the NumPy/SciPy versions currently present in the installation.

Here is the relevant environment output:

```console
> python_embeded\python.exe -c "import numpy; print('numpy:', numpy.__version__)"
numpy: 1.26.4

> python_embeded\python.exe -m pip show scipy
Name: scipy
Version: 1.18.0

> python_embeded\python.exe -m pip check
colour-science 0.4.7 has requirement numpy<3,>=2.0.0, but you have numpy 1.26.4.
opencv-contrib-python 4.13.0.92 has requirement numpy>=2; python_version >= "3.9", but you have numpy 1.26.4.
opencv-python 4.13.0.92 has requirement numpy>=2; python_version >= "3.9", but you have numpy 1.26.4.
opencv-python-headless 4.13.0.92 has requirement numpy>=2; python_version >= "3.9", but you have numpy 1.26.4.
rembg 2.0.74 has requirement numpy<3.0.0,>=2.3.0, but you have numpy 1.26.4.
scipy 1.18.0 has requirement numpy<2.8,>=2.0.0, but you have numpy 1.26.4.
```

There is also an unrelated protobuf conflict from `descript-audiotools`, but that is not involved in this particular startup traceback.

This seems to show that pinning only NumPy to 1.26.4 is no longer sufficient. Other packages in the bundled environment, particularly SciPy 1.18.0, are now being installed at versions that require NumPy 2.x.

Would the intended fix be to also pin SciPy and the other bundled packages to NumPy-1-compatible versions, or should the global NumPy 1.26.4 pin be reconsidered for installations that receive these newer dependencies?

**Comment by Tavris1** [comment]
This is exactly why SciPy==1.17.1 is installed in the initial setup.
If something else does not require SciPy 1.18+, then you can use these commands from the `python_embeded` folder to install SciPy==1.17.1:
```console
.\python.exe -m pip uninstall scipy -y
```
```console
.\python.exe -m pip install scipy==1.17.1
```
